name: ai-portfolio
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - jupyter
  - jupytext
  - ydata-profiling
  - ipykernel
  - scikit-learn
  - nbconvert
  - ruff
  - black
  - requests
  - xgboost
  - kaggle
  - kagglehub
  - plotly
  - pip
  - pip:
      - nbqa
      - notebook
      - tensorflow==2.17.0