name: ai-portfolio
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - jupyter
  - jupytext
  - ydata-profiling
  - ipykernel
  - scikit-learn
  - nbconvert
  - ruff
  - black
  - requests
  - xgboost
  - lightgbm
  - kaggle
  - kagglehub
  - plotly
  - pillow
  - sqlite    
  - pip
  - pip:
      - nbqa
      - notebook
      - tensorflow==2.17.0
      - tensorflow-datasets>=4.9.4
      - torch
      - transformers
      - tf-keras 
      - timm
      - accelerate
      - safetensors
      - diffusers
      - opencv-python
      - ultralytics==8.3.60
      - sqlparse
      - gradio

